### ISSUE TITLE
Что если ввести некорректные данные?

### ISSUE THREAD

**Issue by oleg-tgn** [Kosteeck/OAiP_labs_Lavrukhin#4]
одно и главных требований, программа не должна вылетать, а должна выдавать пользователю корректное сообщение при вводе неверных данных
будет ли программа себя вести корректно, если ввести
"1234567890123456789"
"helloworld"
"123.123"

**Comment by Kosteeck** [comment]
Использовал проверку: 
float x; 
  int result = scanf("%f", &x); 
  if (result == 0) {
	printf("Error message");
  } 
  else {
	//  вычисляем формулу
  }
При вводе символов/букв и т.п. работает отлично, но если начать ввод с числа, а затем написать символы, то программа работает с числом, а последующие символы игнорирует.
Например: 
Ввод: 2fllflfl4fl
Программа работает с числом 2
Вывод:  правильный для числа 2
Является ли это правильным? И как это можно исправить?

**Comment by Kosteeck** [comment]
Нашел решение:
if (getchar() != '\n')
	{
		while (getchar() != '\n');
		printf("Please try again and enter a positive number: ");
		переменная = рекурсии;
	}
