### ISSUE TITLE
Проект

### ISSUE THREAD

**Issue by oleg-tgn** [Kosteeck/OAiP_labs_Lavrukhin#5]
- Именование проекта

- гитигнор

- форматирование кода

подробнее тут

https://github.com/oleg-tgn/for-students/wiki

**Comment by Kosteeck** [comment]
С именованием проекта все было в порядке и гитигнор у меня стоял. Может я что-то сделал не так?

**Comment by oleg-tgn** [comment]
Если будите создавать как [Пустой проект](https://github.com/oleg-tgn/for-students/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D0%B2-Visual-Studio), тогда не будет появляться лишних файлов, которые генерирует Visual Studio
