### ISSUE TITLE
Замечания по отчету

### ISSUE THREAD

**Issue by oleg-tgn** [Kosteeck/OAiP_labs_Lavrukhin#7]
1) Еще раз внимательно требования в вики

2) [Много однотипных замечаний, как у Никиты](https://github.com/Nikita-Vasilchenko/OAiP_labs_Vasilchenko/issues/8)

3) Установите microsoft visio и нарисуйте в ней хорошую блок-схему. Не знаю как Ваша выглядит в оригинале, но в OpenOffice она вот такая 
![2017-10-30 15 05 58](https://user-images.githubusercontent.com/16413346/32169996-db843d42-bd83-11e7-8579-709342b464fa.png)

**Comment by Kosteeck** [comment]
Блок-схему рисовал в visio, вставлял через "специальную вставку"

**Comment by oleg-tgn** [comment]
Странно ведет себя OpenOffice, ну самое простое это можно ее вообще картинкой вставить. 
Ну пусть остается тогда, на всякий сохраните отчет в pdf, я тогда в нем посмотрю
